version: '3.8'

services:
  app:
    build: .
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb+srv://fauziardiansyah302:MPJ5ug9Uic7G5kSt@server.s2mwu.mongodb.net/?retryWrites=true&w=majority&appName=server
      - JWT_SECRET=mysecretkey
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongo_data:
